### ISSUE TITLE
How to do the unvanish

### ISSUE THREAD

**Issue by TheLuckyy11th** [superbobby2000/VanishV2#16]
I do /vanish and I spent around 1 hour going through every command on my server and I can’t find /unvanish. I even tried a command block but they are broken

**Comment by superbobby2000** [comment]
do /v again

**Comment by TheLuckyy11th** [comment]
OMG TY YOU ARE SUPER DUPER SMART AND I LOVE YOU BUT NO HOMOSEXUAL
