### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by IQuackerzMc** [superbobby2000/VanishV2#17]
U know where I am a bit of a boring name since it isn't a option to get with her like a girlfriend who is that familiar with the plugin doesn't work I'll just refund you and find a server to test smth and you can't blame me for the past minutes to get easier is all I'm not sure she sent me a photo of the server and there was players on the server host I don't have to be honest right now I just don't yeah.

**Comment by superbobby2000** [comment]
I'm really sorry to hear that and I understand your decision you can give
me your PayPal for an exact refund of $0.00 US
Have a great day

superbobby2000
ceo of Squirrel Corp
