### ISSUE TITLE
Command /v /vanish doesnt work

### ISSUE THREAD

**Issue by MonoAdrian23** [superbobby2000/VanishV2#18]
V1.10
Pocketmine 3.14.1
When i Type /vanish nothing happens!
BlazinFly and Scorehud Addon is installed but nothing happens

**Comment by superbobby2000** [comment]
do /pl in game and send me a screenshot

**Comment by TheLuckyy11th** [comment]
Adrian r u fucking stupid, u probably didn’t even add it to your server. Your just sped, If that doesn’t work the why r u the only one with this comment. Me and Bobby own a server and it’s working.

                                   - Lucky in super toxic mode

**Comment by MonoAdrian23** [comment]
![Screenshot_20200713-070921_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/87272919-f70c1b80-c4d7-11ea-8cdd-d626d36689cf.jpg)

I have nothing changed in Plugin

**Comment by superbobby2000** [comment]
The plugin is red, that mean he's disabled have you tried checking your console before creating an issue the plugin is probably disabled because your configuration file is outdated you have to delete it to get the new one
