### ISSUE TITLE
ScoreHud support (Hide online too)

### ISSUE THREAD

**Issue by UnEnanoMas** [superbobby2000/VanishV2#19]
The plugin hides you from all places, except the basic ScoreHud with the basic addon, which adds the {online} {max_online}

https://github.com/JackMD/ScoreHud-Addons

![Captura de pantalla (118)](https://user-images.githubusercontent.com/63286108/87872757-9f7c1d00-c9bb-11ea-9f20-c55ffaed8fb7.png)

**Comment by TheLuckyy11th** [comment]
Anyone can see you online If they have perms too, that’s already a thing. Go on another account without OP and it will show 1/20

**Comment by superbobby2000** [comment]
like I said on the infos of VanishV2 v1.10 you have to download my BasicAddon for ScoreHud to get this fixed you can download it here https://github.com/superbobby2000/VanishV2/releases/download/ScoreHud/BasicAddon.php

**Comment by UnEnanoMas** [comment]
ty
