### ISSUE TITLE
Please add this

### ISSUE THREAD

**Issue by ZelkTheElk** [superbobby2000/VanishV2#20]
I want to be able to fully customize this plugin. This includes the [player: vanished] and [player: unvanished] message. As well as the "You have vanished" and the "You unvanished" message. I also want a feature where you can vanish other players, like /vanish player2
Thanks!

**Comment by superbobby2000** [comment]
done

**Comment by ZelkTheElk** [comment]
thanks

**Comment by aidaner** [comment]
wait
