### ISSUE TITLE
Hey! Another suggestion

### ISSUE THREAD

**Issue by ZelkTheElk** [superbobby2000/VanishV2#21]
A few more things I would like added: The ability to change the actionbar text (The hotbar text), the nametag while vanished, and could you remove the VanishV2>> prefix? Thanks :)

**Comment by TheLuckyy11th** [comment]
The plugin is not made for a specific person/server, it’s like a watermark sort of thing. So nobody can change it and make it “custom” to their server. It also “blocks” if people want to say they made it

**Comment by ZelkTheElk** [comment]
uh well

**Comment by ZelkTheElk** [comment]
could you make it a thing? I will not say I made it

**Comment by ZelkTheElk** [comment]
also if you want you could be a dev on my server

**Comment by TheLuckyy11th** [comment]
No, your not the only one that downloads this plugin. If he makes it then there will be other people.

**Comment by ZelkTheElk** [comment]
ill see if the owner wants to

**Comment by TheLuckyy11th** [comment]
Wants to?

**Comment by ZelkTheElk** [comment]
yeah, if he wants to dev my server and add those features

**Comment by TheLuckyy11th** [comment]
He doesn’t want to dev for u, he’s working on his own server

**Comment by superbobby2000** [comment]
like @TheLuckyy11th said I won't remove the prefix because it's not disturbing and don't cause any problems but that's true I forgot the hud thing

**Comment by ZelkTheElk** [comment]
wait

**Comment by ZelkTheElk** [comment]
how about you add a /vinfo or a /vanishinfo that is accessible to all players, and say that you made it there?
The prefix does cause problems on my server as it is distracting.

**Comment by superbobby2000** [comment]
I don't understand how a prefix can be distracting and anyway on won't remove it and won't add useless command such as /vanishinfo

**Comment by TheLuckyy11th** [comment]
No, stop asking. It’s fine how it is, and doesn’t need all this stuff just for u to make it say “LEETSERVER>> vanished”

**Comment by ZelkTheElk** [comment]
fine

**Comment by TheLuckyy11th** [comment]
What’s your server?

**Comment by ZelkTheElk** [comment]
flamemcpe.aternos.me:59371 ill start it real quick

**Comment by ZelkTheElk** [comment]
k go join

**Comment by TheLuckyy11th** [comment]
I can’t join rn, but aternos... LOL. Good luck with your server ;)

**Comment by ZelkTheElk** [comment]
no
