### ISSUE TITLE
The name appears on the UI interface

### ISSUE THREAD

**Issue by UnEnanoMas** [superbobby2000/VanishV2#33]
![image](https://user-images.githubusercontent.com/63286108/101527415-445cbe00-398e-11eb-9910-5d83a34494ae.png)

I have /vanish enabled but in the interface that is looking for users to become tp by clicking on the name, it appears

**Comment by superbobby2000** [comment]
cannot fix that, the plugin you are using is looking for all online players. If I mark vanished players as offline they won't be able to do a lot of things on server
