### ISSUE TITLE
Question/Help

### ISSUE THREAD

**Issue by UnEnanoMas** [superbobby2000/VanishV2#34]
![image](https://user-images.githubusercontent.com/63286108/103486786-a3ccb300-4e00-11eb-9565-ab21877fa181.png)

This has been happening to me for a while now and I wanted to know if there is something wrong.

When you put / vanish and the message "X has abandoned the game" appears as a blank text above that message, I don't know if there is something wrong with my configuration, could you help me?

[config.txt](https://github.com/superbobby2000/VanishV2/files/5762154/config.txt)

I put it in txt because it won't let me upload it in normal xd

**Comment by superbobby2000** [comment]
you added "§7" before the "se ha desconectado" so it make this part of the message gray
