### ISSUE TITLE
Crash at 1.16.220

### ISSUE THREAD

**Issue by UnEnanoMas** [superbobby2000/VanishV2#36]
[Crash VanishV2.txt](https://github.com/superbobby2000/VanishV2/files/6278352/Crash.VanishV2.txt)

Occurs when you open a chest in /vanish

**Comment by superbobby2000** [comment]
are you running the plugin from source?

**Comment by UnEnanoMas** [comment]
If you mean that if I have the plugin in .phar the answer is no

I have it on file, like most plugins

**Comment by superbobby2000** [comment]
you have to update InvMenu virion then

**Comment by superbobby2000** [comment]
or download from poggit

**Comment by UnEnanoMas** [comment]
I did that, but when I clicked on the chest it did not open and a chest appeared behind me, it was very strange, now I record it

**Comment by UnEnanoMas** [comment]
09.04 22:15:09 [Server] Server thread/CRITICAL ErrorException: "Non-static method muqsit\invmenu\InvMenu::readonly() should not be called statically" (EXCEPTION) in "plugins/VanishV2-master/src/superbobby/VanishV2/EventListener" at line 129
09.04 22:15:09 [Server] Server thread/CRITICAL #0 plugins/VanishV2-master/src/superbobby/VanishV2/EventListener(129): pocketmine\utils\Utils::errorExceptionHandler(integer 8192, string[84] Non-static method muqsit\invmenu\InvMenu::readonly() should not be called static, string[113] /plugins/VanishV2-master/src/supe, integer 129, array[10])
09.04 22:15:09 [Server] Server thread/CRITICAL #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): superbobby\VanishV2\EventListener->onInteract(object pocketmine\event\player\PlayerInteractEvent)
09.04 22:15:09 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object superbobby\VanishV2\EventListener, object pocketmine\event\player\PlayerInteractEvent)
09.04 22:15:09 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent)
09.04 22:15:09 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/level/Level(1872): pocketmine\event\Event->call()
09.04 22:15:09 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/Player(2560): pocketmine\level\Level->useItemOn(object pocketmine\math\Vector3, object pocketmine\item\ItemBlock, integer 4, object pocketmine\math\Vector3, object pocketmine\Player, boolean 1)
09.04 22:15:09 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(149): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
09.04 22:15:09 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(106): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
09.04 22:15:09 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
09.04 22:15:09 [Server] Server thread/CRITICAL #9 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
09.04 22:15:09 [Server] Server thread/CRITICAL #10 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
09.04 22:15:09 [Server] Server thread/CRITICAL #11 pmsrc/src/pocketmine/Player(3311): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
09.04 22:15:09 [Server] Server thread/CRITICAL #12 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
09.04 22:15:09 [Server] Server thread/CRITICAL #13 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 81.0.33.238 20885, object raklib\protocol\EncapsulatedPacket, integer 0)
09.04 22:15:09 [Server] Server thread/CRITICAL #14 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
09.04 22:15:09 [Server] Server thread/CRITICAL #15 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
09.04 22:15:09 [Server] Server thread/CRITICAL #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
09.04 22:15:09 [Server] Server thread/CRITICAL #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
09.04 22:15:09 [Server] Server thread/CRITICAL #18 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1618006509.9938)
09.04 22:15:09 [Server] Server thread/CRITICAL #19 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
09.04 22:15:09 [Server] Server thread/CRITICAL #20 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
09.04 22:15:09 [Server] Server thread/CRITICAL #21 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
09.04 22:15:09 [Server] Server thread/CRITICAL #22 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
09.04 22:15:09 [Server] Server thread/CRITICAL #23 pmsrc(11): require(string[117] phar:///PMMP-1.16.220-Latest-Stab)

Whit InvMenu Dev #135

**Comment by superbobby2000** [comment]
it should work if you installed everything the right way. You should download the plugin from poggit instead of running it from source. It's not recommended to run plugins from source with DEVirion on live servers anyways

**Comment by UnEnanoMas** [comment]
I'm going to test it on my other server whitout files, just phar

**Comment by UnEnanoMas** [comment]
Well, if it works, how strange, ok I'll install the phar, thanks for the help

**Comment by superbobby2000** [comment]
np
