### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mikeygio10** [superbobby2000/VanishV2#4]
The fake join msg says it 2 times and not 1

**Comment by superbobby2000** [comment]
send me screens because it's not doing this to me

**Comment by mikeygio10** [comment]
![B14B8309-EF94-49CA-AE07-5E682D312026](https://user-images.githubusercontent.com/46503241/71774410-2b58bb00-2f3c-11ea-9186-8ab9e6c7898f.png)

**Comment by mikeygio10** [comment]
Try it with 2 poeple in the game

**Comment by superbobby2000** [comment]
it's weird

**Comment by mikeygio10** [comment]
Wait do you have the same problem or is it just me

**Comment by superbobby2000** [comment]
idk I didn't tried

**Comment by MistakingManx** [comment]
I actually know exactly where this bug takes place, Superbobby has it so that it sends the broadcast to every online player. Which makes it send multiple times.

**Comment by mikeygio10** [comment]
MistakingManx your pr build works but it does not vanish you

**Comment by superbobby2000** [comment]
fixed and checked with two players, it's supposed to work let me know if I'm wrong
