### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Willtom999** [superbobby2000/VanishV2#42]
Add rename pseudo for vanish

**Comment by superbobby2000** [comment]
I'm not sure what you mean, can you explain?

**Comment by Neonwaltz8** [comment]
I think they meant "rename the vanish command to pseudo" or maybe add another alias, which is odd considering that there's already a /v 
its much more shorter, but oh well

**Comment by superlucky2000** [comment]
Your right, there is another vanish plugin. From my stand point nobody uses the original Vanish plugin because it’s just a invisibility potion 😂 I don’t see the point in renaming the command to something so unrelated to the plugin.
