### ISSUE TITLE
Suggestion for silent join/leave

### ISSUE THREAD

**Issue by Mencoreh** [superbobby2000/VanishV2#46]
At least make the silent join/leave message compatible with CustomAlerts since no one uses the default messages and almost everyone uses CustomAlerts

**Comment by superbobby2000** [comment]
this issue has been fixed already in the latest version

**Comment by Mencoreh** [comment]
Ok, its on poggit? because i read the "Whats new" section and didnt see that

**Comment by superbobby2000** [comment]
yes I just didn't specify it in the "what's new"
