### ISSUE TITLE
465

### ISSUE THREAD

**Issue by DPG896** [superbobby2000/VanishV2#49]
Update the protocol. (Im using the latest version btw) #BlameMOJANG #![Screenshot_20210922-083838.png](https://user-images.githubusercontent.com/82310008/134401626-8d052b3b-eb26-4852-bf60-2caac94bc024.png)

**Comment by Matthww** [comment]
I the pro developer already fixed this for slow developer @superbobby2000

**Comment by superbobby2000** [comment]
:catstare:

**Comment by Matthww** [comment]
![image](https://user-images.githubusercontent.com/3885070/134402401-28166ba5-4c9d-4ffc-838f-5c6b1db39209.png)
