### ISSUE TITLE
{VanishV2.fake_count} does not appear in ScoreHud 7.0.0

### ISSUE THREAD

**Issue by MrBlasyMSK** [superbobby2000/VanishV2#58]
![image](https://user-images.githubusercontent.com/85447029/158385580-19a837f4-575c-47ec-92b1-2c4f897f85ea.png)
```yml
- "§8☆§aConectados§7: §f{VanishV2.fake_count} §9/ §f{scorehud.max_online}"
```

**Comment by sqrrrrl** [comment]
the fake count only appear to non op players and players without the vanish.see permission
