### ISSUE TITLE
The player counter does not work correctly {VanishV2.fake_count}

### ISSUE THREAD

**Issue by MrBlasyMSK** [superbobby2000/VanishV2#59]
The following images are without OP and without any permissions added

![1Screenshot_20220315_151958_com mojang minecraftpe](https://user-images.githubusercontent.com/85447029/158399819-973372b6-d559-41ce-b059-df6f8485cce3.jpg)
![imagen_2022-03-15_152403](https://user-images.githubusercontent.com/85447029/158399841-47840074-fe0f-4425-a392-01f2d440d184.jpg)

If you look at the player counter in Windows 10 there are 2 players, and in Android there is 1 player.
Then I did the test again and this was displayed

![1imagen_2022-03-15_152924](https://user-images.githubusercontent.com/85447029/158400579-31be9309-bb4a-4646-b69b-a85e8a9f0064.jpg)

When i leave the game, the same thing happens, it does not change.

So before closing an issue ask and review it in detail.

**Comment by superbobby2000** [comment]
I shouldn't be the one asking for more detail here. When creating an issue on github for any plugin or software you should always provide the most information possible such as the version of the server software, the version of the plugin, the php version, ect I answered to your previous issue with the information that was provided to me as I know it's working and it's an issue on your side. The only way I can help you solve this issue is by getting more details.

**Comment by MrBlasyMSK** [comment]
So get an issue portfolio and we have to fill it out to describe what is happening, the version and everything you need, I don't know if I have to tell you that I have JIT support enabled either.

Leaving aside that issue, here you have all the information
```
[01:05:06.611] [Server thread/INFO]: This server is running PocketMine-MP
[01:05:06.611] [Server thread/INFO]: Server version: 4.2.3 (git hash: 6c1c0c867e178f8da8b266e962ca13f4b4280ab4)
[01:05:06.611] [Server thread/INFO]: Compatible Minecraft version: 1.18.10 (protocol version: 486)
[01:05:06.611] [Server thread/INFO]: PHP version: 8.0.16
[01:05:06.611] [Server thread/INFO]: PHP JIT: not supported
[01:05:06.611] [Server thread/INFO]: Operating system: linux
```
VanishV2 version: Dev#126

What else do you need to know?

**Comment by superbobby2000** [comment]
Do you mind providing your config for PurePerms, ScoreHud and VanishV2

**Comment by MrBlasyMSK** [comment]
> Do you mind providing your config for PurePerms, ScoreHud and VanishV2

is probably caused by this:

https://github.com/Ifera/ScoreHud/issues/198#issuecomment-1076928770

**Comment by Ifera** [comment]
Fixed in https://github.com/Ifera/ScoreHud/commit/3d64f10c3c9811f27107b27b41189c066e7aee7d

**Comment by MrBlasyMSK** [comment]
Yeah, thx <3
