### ISSUE TITLE
VanushV2 crash (may overwritten by other plugins)

### ISSUE THREAD

**Issue by TukangM** [superbobby2000/VanishV2#61]
```
[19:34:57.899] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\InventoryManager::getWindow()" (EXCEPTION) in "plugins/VanishV2.phar/src/superbobby/VanishV2/libs/muqsit/invmenu/session/network/PlayerNetwork" at line 140
--- Stack trace ---
  #0 plugins/VanishV2.phar/src/superbobby/VanishV2/libs/muqsit/invmenu/InvMenuEventHandler(62): superbobby\VanishV2\libs\muqsit\invmenu\session\network\PlayerNetwork->translateContainerOpen(object superbobby\VanishV2\libs\muqsit\invmenu\session\PlayerSession#153534, object pocketmine\network\mcpe\protocol\ContainerOpenPacket#164513)
  #1 pmsrc/src/event/RegisteredListener(60): superbobby\VanishV2\libs\muqsit\invmenu\InvMenuEventHandler->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent#164515)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#164515)
  #3 pmsrc/src/network/mcpe/NetworkSession(436): pocketmine\event\Event->call()
  #4 pmsrc/src/network/mcpe/InventoryManager(260): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\ContainerOpenPacket#164513)
  #5 pmsrc/src/network/mcpe/InventoryManager(227): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}()
  #6 pmsrc/src/network/mcpe/InventoryManager(267): pocketmine\network\mcpe\InventoryManager->openWindowDeferred(object Closure#164509)
  #7 pmsrc/src/player/Player(2531): pocketmine\network\mcpe\InventoryManager->onCurrentWindowChange(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164477)
  #8 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/type/graphic/BlockActorInvMenuGraphic(56): pocketmine\player\Player->setCurrentWindow(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164477)
  #9 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/PlayerSession(47): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\type\graphic\BlockActorInvMenuGraphic->sendInventory(object pocketmine\player\Player#153553, object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164477)
  #10 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/network/PlayerNetwork(81): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\PlayerSession->DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\{closure}(true)
  #11 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/PlayerSession(60): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\network\PlayerNetwork->waitUntil(int 0, object Closure#164507)
  #12 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/InvMenu(128): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\PlayerSession->setCurrentMenu(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\InvMenuInfo#164505, object Closure#164506)
  #13 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/network/PlayerNetwork(81): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\InvMenu->DaPigGuy\PiggyCrates\libs\muqsit\invmenu\{closure}(true)
  #14 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/InvMenu(136): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\network\PlayerNetwork->waitUntil(int 0, object Closure#164492)
  #15 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/tiles/CrateTile(131): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\InvMenu->send(object pocketmine\player\Player#153553)
  #16 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/EventListener(36): DaPigGuy\PiggyCrates\tiles\CrateTile->previewCrate(object pocketmine\player\Player#153553)
  #17 pmsrc/src/event/RegisteredListener(60): DaPigGuy\PiggyCrates\EventListener->onInteract(object pocketmine\event\player\PlayerInteractEvent#164474)
  #18 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent#164474)
  #19 pmsrc/src/world/World(1930): pocketmine\event\Event->call()
  #20 pmsrc/src/player/Player(1714): pocketmine\world\World->useItemOn(object pocketmine\math\Vector3#164468, object pocketmine\item\ItemBlock#164472, int 1, object pocketmine\math\Vector3#164465, object pocketmine\player\Player#153553, true)
  #21 pmsrc/src/network/mcpe/handler/InGamePacketHandler(443): pocketmine\player\Player->interactBlock(object pocketmine\math\Vector3#164468, int 1, object pocketmine\math\Vector3#164465)
  #22 pmsrc/src/network/mcpe/handler/InGamePacketHandler(320): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData#164459)
  #23 plugins/VanillaX/src/CLADevs/VanillaX/network/handler/InGamePacketHandlerX(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452)
  #24 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): CLADevs\VanillaX\network\handler\InGamePacketHandlerX->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452)
  #25 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object CLADevs\VanillaX\network\handler\InGamePacketHandlerX#163957)
  #26 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452, string[39] .......B.....R..Cr=.B...C...>.3s?...?.U)
  #27 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[101] .Sa..`u:....|...Y..Q].....,.....l.s.m.......f..c0..g..a?1.d......s..:ta)D.)."(..)
  #28 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[102] ..Sa..`u:....|...Y..Q].....,.....l.s.m.......f..c0..g..a?1.d......s..:ta)D.)."(.)
  #29 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#153157)
  #30 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #31 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #32 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1670589297.9083)
  #33 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
  #34 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[13] /home/aep/pm/, string[21] /home/aep/pm/plugins/)
  #35 pmsrc/src/PocketMine(351): pocketmine\server()
  #36 pmsrc(11): require(string[57] phar:///home/aep/pm/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[19:34:57.901] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[19:34:57.921] [Server thread/EMERGENCY]: Please upload the "/home/aep/pm/crashdumps/Fri_Dec_9-12.34.57-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[19:35:02.930] [Server thread/EMERGENCY]: Failed to communicate with crash archive: Could not resolve host: crash.pmmp.io
[19:35:02.931] [Server thread/EMERGENCY]: Forcing server shutdown
[19:35:02.931] [Server thread/INFO]: Disabling DevTools v1.16.0
```
OS ubuntu2204 (linux deploy android)
php 8.0.24 (compiled arm64)
pocketmine  4.12.1 (lastest) Server version: 4.12.1 (git hash: 7ae6425d05cce581854f44c13845635f2ce0eef2)

overwritten by other plugin (maybe)
https://poggit.pmmp.io/ci/BlockHorizons/InvSee/InvSee/dev:79 release version
https://poggit.pmmp.io/p/PiggyCrates/3.0.3 v 3.3

**Comment by ItsRealNise** [comment]
just update InvMenu for InvSee and PiggyCrates

**Comment by TukangM** [comment]
The all plugin updated. maybe infected by InvFix
So I try tomorrow

**Comment by ItsRealNise** [comment]
yeah you must update a InvMenu

**Comment by TukangM** [comment]
> yeah you must update a InvMenu


impossible. vanishv2 likely use muqsit lib.
![image](https://user-images.githubusercontent.com/91467886/206998094-3218c705-4c60-42c0-9125-68271ee248ce.png)

**Comment by TukangM** [comment]
<details>
  <summary>Logs</summary>
> ```
> [19:34:57.899] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\InventoryManager::getWindow()" (EXCEPTION) in "plugins/VanishV2.phar/src/superbobby/VanishV2/libs/muqsit/invmenu/session/network/PlayerNetwork" at line 140
> --- Stack trace ---
>   #0 plugins/VanishV2.phar/src/superbobby/VanishV2/libs/muqsit/invmenu/InvMenuEventHandler(62): superbobby\VanishV2\libs\muqsit\invmenu\session\network\PlayerNetwork->translateContainerOpen(object superbobby\VanishV2\libs\muqsit\invmenu\session\PlayerSession#153534, object pocketmine\network\mcpe\protocol\ContainerOpenPacket#164513)
>   #1 pmsrc/src/event/RegisteredListener(60): superbobby\VanishV2\libs\muqsit\invmenu\InvMenuEventHandler->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent#164515)
>   #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent#164515)
>   #3 pmsrc/src/network/mcpe/NetworkSession(436): pocketmine\event\Event->call()
>   #4 pmsrc/src/network/mcpe/InventoryManager(260): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\ContainerOpenPacket#164513)
>   #5 pmsrc/src/network/mcpe/InventoryManager(227): pocketmine\network\mcpe\InventoryManager->pocketmine\network\mcpe\{closure}()
>   #6 pmsrc/src/network/mcpe/InventoryManager(267): pocketmine\network\mcpe\InventoryManager->openWindowDeferred(object Closure#164509)
>   #7 pmsrc/src/player/Player(2531): pocketmine\network\mcpe\InventoryManager->onCurrentWindowChange(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164477)
>   #8 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/type/graphic/BlockActorInvMenuGraphic(56): pocketmine\player\Player->setCurrentWindow(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164477)
>   #9 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/PlayerSession(47): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\type\graphic\BlockActorInvMenuGraphic->sendInventory(object pocketmine\player\Player#153553, object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\inventory\InvMenuInventory#164477)
>   #10 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/network/PlayerNetwork(81): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\PlayerSession->DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\{closure}(true)
>   #11 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/PlayerSession(60): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\network\PlayerNetwork->waitUntil(int 0, object Closure#164507)
>   #12 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/InvMenu(128): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\PlayerSession->setCurrentMenu(object DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\InvMenuInfo#164505, object Closure#164506)
>   #13 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/session/network/PlayerNetwork(81): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\InvMenu->DaPigGuy\PiggyCrates\libs\muqsit\invmenu\{closure}(true)
>   #14 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/libs/muqsit/invmenu/InvMenu(136): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\session\network\PlayerNetwork->waitUntil(int 0, object Closure#164492)
>   #15 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/tiles/CrateTile(131): DaPigGuy\PiggyCrates\libs\muqsit\invmenu\InvMenu->send(object pocketmine\player\Player#153553)
>   #16 plugins/PiggyCrates_dev-117.phar/src/DaPigGuy/PiggyCrates/EventListener(36): DaPigGuy\PiggyCrates\tiles\CrateTile->previewCrate(object pocketmine\player\Player#153553)
>   #17 pmsrc/src/event/RegisteredListener(60): DaPigGuy\PiggyCrates\EventListener->onInteract(object pocketmine\event\player\PlayerInteractEvent#164474)
>   #18 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerInteractEvent#164474)
>   #19 pmsrc/src/world/World(1930): pocketmine\event\Event->call()
>   #20 pmsrc/src/player/Player(1714): pocketmine\world\World->useItemOn(object pocketmine\math\Vector3#164468, object pocketmine\item\ItemBlock#164472, int 1, object pocketmine\math\Vector3#164465, object pocketmine\player\Player#153553, true)
>   #21 pmsrc/src/network/mcpe/handler/InGamePacketHandler(443): pocketmine\player\Player->interactBlock(object pocketmine\math\Vector3#164468, int 1, object pocketmine\math\Vector3#164465)
>   #22 pmsrc/src/network/mcpe/handler/InGamePacketHandler(320): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemTransactionData#164459)
>   #23 plugins/VanillaX/src/CLADevs/VanillaX/network/handler/InGamePacketHandlerX(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452)
>   #24 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): CLADevs\VanillaX\network\handler\InGamePacketHandlerX->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452)
>   #25 pmsrc/src/network/mcpe/NetworkSession(418): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object CLADevs\VanillaX\network\handler\InGamePacketHandlerX#163957)
>   #26 pmsrc/src/network/mcpe/NetworkSession(374): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452, string[39] .......B.....R..Cr=.B...C...>.3s?...?.U)
>   #27 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[101] .Sa..`u:....|...Y..Q].....,.....l.s.m.......f..c0..g..a?1.d......s..:ta)D.)."(..)
>   #28 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[102] ..Sa..`u:....|...Y..Q].....,.....l.s.m.......f..c0..g..a?1.d......s..:ta)D.)."(.)
>   #29 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#153157)
>   #30 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
>   #31 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
>   #32 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1670589297.9083)
>   #33 pmsrc/src/Server(1061): pocketmine\Server->tickProcessor()
>   #34 pmsrc/src/PocketMine(328): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[13] /home/aep/pm/, string[21] /home/aep/pm/plugins/)
>   #35 pmsrc/src/PocketMine(351): pocketmine\server()
>   #36 pmsrc(11): require(string[57] phar:///home/aep/pm/PocketMine-MP.phar/src/PocketMine.php)
> --- End of exception information ---
> [19:34:57.901] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
> [19:34:57.921] [Server thread/EMERGENCY]: Please upload the "/home/aep/pm/crashdumps/Fri_Dec_9-12.34.57-UTC_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
> [19:35:02.930] [Server thread/EMERGENCY]: Failed to communicate with crash archive: Could not resolve host: crash.pmmp.io
> [19:35:02.931] [Server thread/EMERGENCY]: Forcing server shutdown
> [19:35:02.931] [Server thread/INFO]: Disabling DevTools v1.16.0
> ```
> 
> OS ubuntu2204 (linux deploy android) php 8.0.24 (compiled arm64) pocketmine 4.12.1 (lastest) Server version: 4.12.1 (git hash: 7ae6425d05cce581854f44c13845635f2ce0eef2)
> 
> overwritten by other plugin (maybe) https://poggit.pmmp.io/ci/BlockHorizons/InvSee/InvSee/dev:79 release version https://poggit.pmmp.io/p/PiggyCrates/3.0.3 v 3.3

<details>
maybe can explain this
```
#23 plugins/VanillaX/src/CLADevs/VanillaX/network/handler/InGamePacketHandlerX(164): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#164452)
```
forgot this. this plugin is causing a lot of errors for all plugins

**Comment by ItsRealNise** [comment]
just update your invmenu for vanish, piggycrates, invsee
