### ISSUE TITLE
VanishV2 it does not work

### ISSUE THREAD

**Issue by Jan20202020** [superbobby2000/VanishV2#8]
I do not know what I'm doing wrong
Please help me.
![Screenshot_20200430-232534_PocketMine-MP](https://user-images.githubusercontent.com/64615462/80761340-ade43680-8b3a-11ea-8d93-0cbd5baf5611.jpg)

**Comment by superbobby2000** [comment]
are you using the version v1.6 of VanishV2

**Comment by Jan20202020** [comment]
where can I see that? i downloaded it from pmmp.

**Comment by superbobby2000** [comment]
https://poggit.pmmp.io/p/VanishV2/1.6

**Comment by Jan20202020** [comment]
No, it doesn't work ):

**Comment by superbobby2000** [comment]
do /pl and /ver in your console

**Comment by Jan20202020** [comment]
![Screenshot_20200501-000651_PocketMine-MP](https://user-images.githubusercontent.com/64615462/80763925-e3d7e980-8b3f-11ea-9bf7-ca6e58ad3f0c.jpg)

**Comment by superbobby2000** [comment]
the plugin is enabled it's supposed to work

**Comment by Jan20202020** [comment]
oh sorry, now it suddenly works. thank you.

**Comment by superbobby2000** [comment]
np
